### ISSUE TITLE
`log2` may return incorrect values for partial vectors

### ISSUE THREAD

**Issue by dubosipsl** [chriselrod/SLEEFPirates.jl#35] opened 2023-10-29 19:29 UTC
With :
```julia
using VectorizationBase
using SLEEFPirates

x=range(Float32(0.1), Float32(0.9),4)
@info log2 Vec(map(log2, x)...) log2(Vec(x...))
```
I get incorrect (not inaccurate) results :
```
┌ Info: log2
│   Vec(map(log2, x)...) = Vec{4, Float32}<-3.321928f0, -1.447459f0, -0.6589631f0, -0.15200312f0>
└   log2(Vec(x...)) = Vec{4, Float32}<-0.32192805f0, 0.552541f0, 0.3410369f0, -0.15200312f0>
```
Note that the vector length (4xFloat32) is shorter than my native vector length (8xFloat32). The results with a full vector are correct. Maybe this is expected ?

This is with Julia v1.9.1, SLEEFPirates v0.6.39

btw thanks for developing SLEEFPirates.

**Comment by chriselrod** [comment] 2023-10-29 20:15
No, it is not expected.

**Comment by chriselrod** [comment] 2023-10-29 21:06
I can reproduce when pretending I do not have AVX512
```julia
julia> using VectorizationBase, SLEEFPirates, HostCPUFeatures, Static

julia> x=range(Float32(0.1), Float32(0.9),4)
0.1f0:0.26666668f0:0.9f0

julia> @info log2 Vec(map(log2, x)...) log2(Vec(x...))
┌ Info: log2
│   Vec(map(log2, x)...) = Vec{4, Float32}<-3.321928f0, -1.447459f0, -0.6589631f0, -0.15200312f0>
└   log2(Vec(x...)) = Vec{4, Float32}<-3.321928f0, -1.447459f0, -0.6589631f0, -0.15200312f0>

julia> HostCPUFeatures.has_feature(::Val{:x86_64_avx512f}) = static(false)

julia> HostCPUFeatures.has_feature(::Val{:x86_64_avx512dq}) = static(false)

julia> @info log2 Vec(map(log2, x)...) log2(Vec(x...))
┌ Info: log2
│   Vec(map(log2, x)...) = Vec{4, Float32}<-3.321928f0, -1.447459f0, -0.6589631f0, -0.15200312f0>
└   log2(Vec(x...)) = Vec{4, Float32}<-0.32192805f0, 0.552541f0, 0.3410369f0, -0.15200312f0>
```
which helps narrow it down to a non-AVX512 codepath.

**Comment by chriselrod** [comment] 2023-10-29 21:09
But, as you note, it curiously happens for 128 bit but not 256:
```julia
julia> xx = vcat(x,x);

julia> @info log2 Vec(map(log2, xx)...) log2(Vec(xx...))
┌ Info: log2
│   Vec(map(log2, xx)...) = Vec{8, Float32}<-3.321928f0, -1.447459f0, -0.6589631f0, -0.15200312f0, -3.321928f0, -1.447459f0, -0.6589631f0, -0.15200312f0>
└   log2(Vec(xx...)) = Vec{8, Float32}<-3.321928f0, -1.447459f0, -0.6589631f0, -0.15200312f0, -3.321928f0, -1.447459f0, -0.6589631f0, -0.15200312f0>
```

**Comment by chriselrod** [comment] 2023-10-29 21:51
Should be fixed by https://github.com/JuliaSIMD/VectorizationBase.jl/commit/a75ea4ec9578b8846e2d259b96726febdbf9494b

**Comment by chriselrod** [comment] 2023-10-29 21:57
Also implemented a secondary fix here that avoids the method that was broken, because we shouldn't even be calling it anyway.

**Closed as completed** 2023-10-29 21:57 UTC
